<a href="https://colab.research.google.com/github/PhiWhyyy/Analyzing-market-trends/blob/main/PhiWhyyy_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import csv
with open('/content/phiwhyyy-subscriber-stats.csv', 'r') as f:
  reader = csv.reader(f)
  for row in reader:
    print(row)

['period_start', 'period_end', 'followers_gained', 'followers_lost', 'followers_net', 'followers_total', 'subscribers_gained', 'subscribers_lost', 'subscribers_net', 'subscribers_total', 'referred_members_gained', 'referred_members_lost', 'referred_members_net', 'referred_members_total', 'referred_member_earnings']
['2024-06-01', '2024-06-30', '0', '0', '0', '177', '0', '0', '0', '11', '0', '0', '0', '0', '$0.00']
['2024-05-01', '2024-05-31', '1', '0', '1', '177', '0', '0', '0', '11', '0', '0', '0', '0', '$0.00']
['2024-04-01', '2024-04-30', '3', '0', '3', '176', '0', '0', '0', '11', '0', '0', '0', '0', '$0.00']
['2024-03-01', '2024-03-31', '4', '0', '4', '173', '0', '0', '0', '11', '0', '0', '0', '0', '$0.00']
['2024-02-01', '2024-02-29', '2', '0', '2', '169', '0', '0', '0', '11', '0', '0', '0', '0', '$0.00']
['2024-01-01', '2024-01-31', '6', '0', '6', '167', '1', '0', '1', '11', '0', '0', '0', '0', '$0.00']
['2023-12-01', '2023-12-31', '0', '1', '-1', '161', '0', '1', '-1', '10', '0', '0', '0', '0', '$0.00']
['2023-11-01', '2023-11-30', '1', '0', '1', '162', '0', '0', '0', '11', '0', '0', '0', '0', '$0.00']
['2023-10-01', '2023-10-31', '8', '0', '8', '161', '1', '0', '1', '11', '0', '0', '0', '0', '$0.00']
['2023-09-01', '2023-09-30', '4', '0', '4', '153', '0', '0', '0', '10', '0', '0', '0', '0', '$0.00']
['2023-08-01', '2023-08-31', '8', '0', '8', '149', '1', '1', '0', '10', '0', '0', '0', '0', '$0.00']
['2023-07-01', '2023-07-31', '2', '1', '1', '141', '1', '0', '1', '10', '0', '0', '0', '0', '$0.00']
['2023-06-01', '2023-06-30', '4', '0', '4', '140', '0', '0', '0', '9', '0', '0', '0', '0', '$0.00']
['2023-05-01', '2023-05-31', '2', '0', '2', '136', '0', '0', '0', '9', '0', '0', '0', '0', '$0.00']
['2023-04-01', '2023-04-30', '12', '1', '11', '134', '0', '0', '0', '9', '0', '0', '0', '0', '$0.00']
['2023-03-01', '2023-03-31', '4', '1', '3', '123', '1', '0', '1', '9', '0', '0', '0', '0', '$0.00']
['2023-02-01', '2023-02-28', '0', '0', '0', '120', '0', '0', '0', '8', '0', '0', '0', '0', '$0.00']
['2023-01-01', '2023-01-31', '1', '0', '1', '120', '0', '0', '0', '8', '0', '0', '0', '0', '$0.00']
['2022-12-01', '2022-12-31', '2', '0', '2', '119', '0', '0', '0', '8', '0', '0', '0', '0', '$0.00']
['2022-11-01', '2022-11-30', '3', '0', '3', '117', '1', '1', '0', '8', '0', '0', '0', '0', '$0.00']
['2022-10-01', '2022-10-31', '4', '0', '4', '114', '0', '1', '-1', '8', '0', '0', '0', '0', '$0.00']
['2022-09-01', '2022-09-30', '4', '0', '4', '110', '0', '0', '0', '9', '0', '0', '0', '0', '$0.00']
['2022-08-01', '2022-08-31', '12', '0', '12', '106', '2', '0', '2', '9', '0', '0', '0', '0', '$0.00']
['2022-07-01', '2022-07-31', '15', '0', '15', '94', '1', '0', '1', '7', '0', '0', '0', '0', '$0.00']
['2022-06-01', '2022-06-30', '17', '0', '17', '79', '2', '0', '2', '6', '0', '0', '0', '0', '$0.00']
['2022-05-01', '2022-05-31', '26', '0', '26', '62', '2', '0', '2', '4', '0', '0', '0', '0', '$0.00']
['2022-04-01', '2022-04-30', '12', '0', '12', '36', '1', '0', '1', '2', '0', '0', '0', '0', '$0.00']
['2022-03-01', '2022-03-31', '1', '0', '1', '24', '0', '0', '0', '1', '0', '0', '0', '0', '$0.00']
['2022-02-01', '2022-02-28', '3', '0', '3', '23', '0', '0', '0', '1', '0', '0', '0', '0', '$0.00']
['2022-01-01', '2022-01-31', '2', '0', '2', '20', '0', '0', '0', '1', '0', '0', '0', '0', '$0.00']
['2021-12-01', '2021-12-31', '6', '1', '5', '18', '2', '1', '1', '1', '0', '0', '0', '0', '$0.00']
['2021-11-01', '2021-11-30', '6', '1', '5', '13', '0', '0', '0', '0', '0', '0', '0', '0', '$0.00']
['2021-10-01', '2021-10-31', '5', '0', '5', '8', '0', '0', '0', '0', '0', '0', '0', '0', '$0.00']
['2021-09-01', '2021-09-30', '0', '0', '0', '3', '0', '0', '0', '0', '0', '0', '0', '0', '$0.00']
['2021-08-01', '2021-08-31', '1', '1', '0', '3', '1', '1', '0', '0', '0', '0', '0', '0', '$0.00']
['2021-07-01', '2021-07-31', '1', '0', '1', '3', '0', '0', '0', '0', '0', '0', '0', '0', '$0.00']
['2021-06-01', '2021-06-30', '2', '0', '2', '2', '0', '0', '0', '0', '0', '0', '0', '0', '$0.00']

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
path ="/content/phiwhyyy-subscriber-stats.csv"
df = pd.read_csv(path)
df.drop(columns=["Unnamed: 0"], inplace=True, errors='ignore')
df.head(7828)

,period_start,period_end,followers_gained,followers_lost,followers_net,followers_total,subscribers_gained,subscribers_lost,subscribers_net,subscribers_total,referred_members_gained,referred_members_lost,referred_members_net,referred_members_total,referred_member_earnings
0,2024-06-01,2024-06-30,0,0,0,177,0,0,0,11,0,0,0,0,$0.00
1,2024-05-01,2024-05-31,1,0,1,177,0,0,0,11,0,0,0,0,$0.00
2,2024-04-01,2024-04-30,3,0,3,176,0,0,0,11,0,0,0,0,$0.00
3,2024-03-01,2024-03-31,4,0,4,173,0,0,0,11,0,0,0,0,$0.00
4,2024-02-01,2024-02-29,2,0,2,169,0,0,0,11,0,0,0,0,$0.00
5,2024-01-01,2024-01-31,6,0,6,167,1,0,1,11,0,0,0,0,$0.00
6,2023-12-01,2023-12-31,0,1,-1,161,0,1,-1,10,0,0,0,0,$0.00
7,2023-11-01,2023-11-30,1,0,1,162,0,0,0,11,0,0,0,0,$0.00
8,2023-10-01,2023-10-31,8,0,8,161,1,0,1,11,0,0,0,0,$0.00
9,2023-09-01,2023-09-30,4,0,4,153,0,0,0,10,0,0,0,0,$0.00
10,2023-08-01,2023-08-31,8,0,8,149,1,1,0,10,0,0,0,0,$0.00
11,2023-07-01,2023-07-31,2,1,1,141,1,0,1,10,0,0,0,0,$0.00
12,2023-06-01,2023-06-30,4,0,4,140,0,0,0,9,0,0,0,0,$0.00
13,2023-05-01,2023-05-31,2,0,2,136,0,0,0,9,0,0,0,0,$0.00
14,2023-04-01,2023-04-30,12,1,11,134,0,0,0,9,0,0,0,0,$0.00
15,2023-03-01,2023-03-31,4,1,3,123,1,0,1,9,0,0,0,0,$0.00
16,2023-02-01,2023-02-28,0,0,0,120,0,0,0,8,0,0,0,0,$0.00
17,2023-01-01,2023-01-31,1,0,1,120,0,0,0,8,0,0,0,0,$0.00
18,2022-12-01,2022-12-31,2,0,2,119,0,0,0,8,0,0,0,0,$0.00
19,2022-11-01,2022-11-30,3,0,3,117,1,1,0,8,0,0,0,0,$0.00
20,2022-10-01,2022-10-31,4,0,4,114,0,1,-1,8,0,0,0,0,$0.00
21,2022-09-01,2022-09-30,4,0,4,110,0,0,0,9,0,0,0,0,$0.00
22,2022-08-01,2022-08-31,12,0,12,106,2,0,2,9,0,0,0,0,$0.00
23,2022-07-01,2022-07-31,15,0,15,94,1,0,1,7,0,0,0,0,$0.00
24,2022-06-01,2022-06-30,17,0,17,79,2,0,2,6,0,0,0,0,$0.00
25,2022-05-01,2022-05-31,26,0,26,62,2,0,2,4,0,0,0,0,$0.00
26,2022-04-01,2022-04-30,12,0,12,36,1,0,1,2,0,0,0,0,$0.00
27,2022-03-01,2022-03-31,1,0,1,24,0,0,0,1,0,0,0,0,$0.00
28,2022-02-01,2022-02-28,3,0,3,23,0,0,0,1,0,0,0,0,$0.00
29,2022-01-01,2022-01-31,2,0,2,20,0,0,0,1,0,0,0,0,$0.00
30,2021-12-01,2021-12-31,6,1,5,18,2,1,1,1,0,0,0,0,$0.00
31,2021-11-01,2021-11-30,6,1,5,13,0,0,0,0,0,0,0,0,$0.00
32,2021-10-01,2021-10-31,5,0,5,8,0,0,0,0,0,0,0,0,$0.00
33,2021-09-01,2021-09-30,0,0,0,3,0,0,0,0,0,0,0,0,$0.00
34,2021-08-01,2021-08-31,1,1,0,3,1,1,0,0,0,0,0,0,$0.00
35,2021-07-01,2021-07-31,1,0,1,3,0,0,0,0,0,0,0,0,$0.00
36,2021-06-01,2021-06-30,2,0,2,2,0,0,0,0,0,0,0,0,$0.00

In [8]:
mean_total = df['followers_gained'].mean()
print("Mean of all Followers gained:", mean_total)

Mean of all Followers gained: 4.972972972972973

In [11]:
mode_total = df['followers_gained'].mode()
print("Mode of all Followers gained:", mode_total)

Mode of all Followers gained: 0    1
1    2
2    4
Name: followers_gained, dtype: int64

In [15]:
%ls

phiwhyyy-subscriber-stats.csv  sample_data/